import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Juan About Price Page",
  description: "Generated by About Price Page",
};

export default function PricePage() {
    return (
        <div className="text-2xl">Price Page</div>
    )
}