import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Juan About Page",
  description: "Generated by About Page",
};

export default function page() {
    return (
        <div className="text-2xl">About Page</div>
    )
}
