import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Juan About Contact Page",
  description: "Generated by About Contact Page",
  
};

export default function ContactPage() {
    return (
        <div className="text-2xl">Contact Page</div>
    )
}